### ISSUE TITLE
在发送转账交易时一直报错

### ISSUE THREAD

**Issue by LiuBoPOP** [Elizabet1926/Solana#1]
error = "Error: failed to get recent blockhash: TypeError: Load failed"
好像是Sol的获取recent blockhash 的节点更换了 但是我一直没有找到这个节点应该在哪里替换？

**Comment by Elizabet1926** [comment]
```
solanaWeb.solanaTransfer(privateKey: privateKey,
                         toAddress: toAddress,
                         amount: amount,
                         endpoint: SolanaMainNetValue) { [weak self] state, txid, error in
    guard let self = self else { return }
    print("state = \(state)")
    print("txid = \(txid)")
    if state {
        self.hashLabel.text = txid
    } else {
        self.hashLabel.text = error
    }
}
In this code, replace SolanaMainNetValue with the desired Solana endpoint URL, such as a mainnet or testnet endpoint, to change the network environment where the transfer will be sent.  YOU SHOULD BUY Solana endpoint URL IN  https://www.quicknode.com/
Let me know if you'd like further customization!
```

**Comment by Elizabet1926** [comment]
@LiuBoPOP 

```
solanaWeb.solanaTransfer(privateKey: privateKey,
                         toAddress: toAddress,
                         amount: amount,
                         endpoint: SolanaMainNetValue) { [weak self] state, txid, error in
    guard let self = self else { return }
    print("state = \(state)")
    print("txid = \(txid)")
    if state {
        self.hashLabel.text = txid
    } else {
        self.hashLabel.text = error
    }
}
```
In this code, replace SolanaMainNetValue with the desired Solana endpoint URL, such as a mainnet or testnet endpoint, to change the network environment where the transfer will be sent.  YOU SHOULD BUY Solana endpoint URL IN  https://www.quicknode.com/

Let me know if you'd like further customization!

**Comment by Elizabet1926** [comment]
Today, I used the node "https://solana.maiziqianbao.net/" to test SOL transfers and SPL Token transfers, both of which were successful. However, SPL Token transfers using this node are relatively slow, taking about 20 seconds. Therefore, I recommend purchasing nodes from https://www.quicknode.com/. The latest demo now uses the node "https://solana.maiziqianbao.net/." You can download the latest demo to check it out.

**Comment by Elizabet1926** [comment]
If you have any further questions, feel free to contact me again.
